<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateImportInvoiceTbl extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('import_invoices', function (Blueprint $table) {
            $table->increments('id');
			$table->integer('cf_agent_id')->unsigned()->index();
            $table->foreign('cf_agent_id')->references('id')->on('clients')->onDelete('cascade');            
			$table->integer('cf_sub_agent_id')->unsigned()->index();
            $table->foreign('cf_sub_agent_id')->references('id')->on('clients')->onDelete('cascade');            
			$table->integer('consignee_id')->unsigned()->index();
            $table->foreign('consignee_id')->references('id')->on('clients')->onDelete('cascade');            
            $table->string('salestax_reg_no')->nullable();
            $table->string('invoice_no');
           $table->integer('invoice_date');
             $table->string('ref_no')->nullable();
            $table->string('exchangerate')->nullable();
            $table->string('bl_no')->nullable();
            $table->string('ntn_no')->nullable();
            $table->string('salestax_no')->nullable();
            $table->string('tax_counter_no')->nullable();
            $table->string('vesselname')->nullable();
            $table->string('voyage_no')->nullable();
            $table->string('vir_no')->nullable();
            $table->text('demurrage_charges_paid_at')->nullable();
            $table->text('demurrage_charges_20')->nullable();
            $table->text('demurrage_charges_40')->nullable();
            $table->text('demurrage_charges_45')->nullable();
            $table->float('demurrage_charges_amount_usd')->nullable();
            $table->float('demurrage_charges_amount_pkr')->nullable();
            $table->float('demurrage_charges_discount_amount')->nullable();
            $table->text('demurrage_charges_value_excld')->nullable();
            $table->text('demurrage_charges_ST_n_fed')->nullable();
            $table->text('demurrage_charges_provisionalsalestaxamount')->nullable();
            $table->text('demurrage_charges_value_inc_tax')->nullable();
            $table->text('storage_charges_paid_at')->nullable();
            $table->text('storage_charges_20')->nullable();
            $table->text('storage_charges_40')->nullable();
            $table->text('storage_charges_45')->nullable();
            $table->float('storage_charges_amount_usd')->nullable();
            $table->float('storage_charges_amount_pkr')->nullable();
            $table->float('storage_charges_discount_amount')->nullable();
            $table->text('storage_charges_value_excld')->nullable();
            $table->text('storage_charges_ST_n_fed')->nullable();
            $table->text('storage_charges_provisionalsalestaxamount')->nullable();
            $table->text('storage_charges_value_inc_tax')->nullable();
            $table->text('wharfage_charges_paid_at')->nullable();
            $table->text('wharfage_charges_20')->nullable();
            $table->text('wharfage_charges_40')->nullable();
            $table->text('wharfage_charges_45')->nullable();
            $table->float('wharfage_charges_amount_usd')->nullable();
            $table->float('wharfage_charges_amount_pkr')->nullable();
            $table->float('wharfage_charges_discount_amount')->nullable();
            $table->text('wharfage_charges_value_excld')->nullable();
            $table->text('wharfage_charges_ST_n_fed')->nullable();
            $table->text('wharfage_charges_provisionalsalestaxamount')->nullable();
            $table->text('wharfage_charges_value_inc_tax')->nullable();
            $table->text('terminalservice_paid_at')->nullable();
            $table->text('terminalservice_20')->nullable();
            $table->text('terminalservice_40')->nullable();
            $table->text('terminalservice_45')->nullable();
            $table->float('terminalservice_amount_usd')->nullable();
            $table->float('terminalservice_amount_pkr')->nullable();
            $table->float('terminalservice_discount_amount')->nullable();
            $table->text('terminalservice_value_excld')->nullable();
            $table->text('terminalservice_ST_n_fed')->nullable();
            $table->text('terminalservice_provisionalsalestaxamount')->nullable();
            $table->text('terminalservice_value_inc_tax')->nullable();
            $table->text('docs_charges_paid_at')->nullable();
            $table->text('docs_charges_20')->nullable();
            $table->text('docs_charges_40')->nullable();
            $table->text('docs_charges_45')->nullable();
            $table->float('docs_charges_amount_usd')->nullable();
            $table->float('docs_charges_amount_pkr')->nullable();
            $table->float('docs_charges_discount_amount')->nullable();
            $table->text('docs_charges_value_excld')->nullable();
            $table->text('docs_charges_ST_n_fed')->nullable();
            $table->text('docs_charges_provisionalsalestaxamount')->nullable();
            $table->text('docs_charges_value_inc_tax')->nullable();
            $table->text('truck_in_charges_paid_at')->nullable();
            $table->text('truck_in_charges_20')->nullable();
            $table->text('truck_in_charges_40')->nullable();
            $table->text('truck_in_charges_45')->nullable();
            $table->float('truck_in_charges_amount_usd')->nullable();
            $table->float('truck_in_charges_amount_pkr')->nullable();
            $table->float('truck_in_charges_discount_amount')->nullable();
            $table->text('truck_in_charges_value_excld')->nullable();
            $table->text('truck_in_charges_ST_n_fed')->nullable();
            $table->text('truck_in_charges_provisionalsalestaxamount')->nullable();
            $table->text('truck_in_charges_value_inc_tax')->nullable();
            $table->text('scanner_infstrc_charges_paid_at')->nullable();
            $table->text('scanner_infstrc_charges_20')->nullable();
            $table->text('scanner_infstrc_charges_40')->nullable();
            $table->text('scanner_infstrc_charges_45')->nullable();
            $table->float('scanner_infstrc_charges_amount_usd')->nullable();
            $table->float('scanner_infstrc_charges_amount_pkr')->nullable();
            $table->float('scanner_infstrc_charges_discount_amount')->nullable();
            $table->text('scanner_infstrc_charges_value_excld')->nullable();
            $table->text('scanner_infstrc_charges_ST_n_fed')->nullable();
            $table->text('scanner_infstrc_charges_provisionalsalestaxamount')->nullable();
            $table->text('scanner_infstrc_charges_value_inc_tax')->nullable();
            $table->text('fuelsurcharge_charges_paid_at')->nullable();
            $table->text('fuelsurcharge_charges_20')->nullable();
            $table->text('fuelsurcharge_charges_40')->nullable();
            $table->text('fuelsurcharge_charges_45')->nullable();
            $table->float('fuelsurcharge_charges_amount_usd')->nullable();
            $table->float('fuelsurcharge_charges_amount_pkr')->nullable();
            $table->float('fuelsurcharge_charges_discount_amount')->nullable();
            $table->text('fuelsurcharge_charges_value_excld')->nullable();
            $table->text('fuelsurcharge_charges_ST_n_fed')->nullable();
            $table->text('fuelsurcharge_charges_provisionalsalestaxamount')->nullable();
            $table->text('fuelsurcharge_charges_value_inc_tax')->nullable();
            $table->text('datapro_charges_paid_at')->nullable();
            $table->text('datapro_charges_20')->nullable();
            $table->text('datapro_charges_40')->nullable();
            $table->text('datapro_charges_45')->nullable();
            $table->float('datapro_charges_amount_usd')->nullable();
            $table->float('datapro_charges_amount_pkr')->nullable();
            $table->float('datapro_charges_discount_amount')->nullable();
            $table->text('datapro_charges_value_excld')->nullable();
            $table->text('datapro_charges_ST_n_fed')->nullable();
            $table->text('datapro_charges_provisionalsalestaxamount')->nullable();
            $table->text('datapro_charges_value_inc_tax')->nullable();
            $table->text('scanning_exm_charges_paid_at')->nullable();
            $table->text('scanning_exm_charges_20')->nullable();
            $table->text('scanning_exm_charges_40')->nullable();
            $table->text('scanning_exm_charges_45')->nullable();
            $table->float('scanning_exm_charges_amount_usd')->nullable();
            $table->float('scanning_exm_charges_amount_pkr')->nullable();
            $table->float('scanning_exm_charges_discount_amount')->nullable();
            $table->text('scanning_exm_charges_value_excld')->nullable();
            $table->text('scanning_exm_charges_ST_n_fed')->nullable();
            $table->text('scanning_exm_charges_provisionalsalestaxamount')->nullable();
            $table->text('scanning_exm_charges_value_inc_tax')->nullable();
            $table->text('custom_seal_charges_paid_at')->nullable();
            $table->text('custom_seal_charges_20')->nullable();
            $table->text('custom_seal_charges_40')->nullable();
            $table->text('custom_seal_charges_45')->nullable();
            $table->float('custom_seal_charges_amount_usd')->nullable();
            $table->float('custom_seal_charges_amount_pkr')->nullable();
            $table->float('custom_seal_charges_discount_amount')->nullable();
            $table->text('custom_seal_charges_value_excld')->nullable();
            $table->text('custom_seal_charges_ST_n_fed')->nullable();
            $table->text('custom_seal_charges_provisionalsalestaxamount')->nullable();
            $table->text('custom_seal_charges_value_inc_tax')->nullable();
            $table->text('survey_charges_paid_at')->nullable();
            $table->text('survey_charges_20')->nullable();
            $table->text('survey_charges_40')->nullable();
            $table->text('survey_charges_45')->nullable();
            $table->float('survey_charges_amount_usd')->nullable();
            $table->float('survey_charges_amount_pkr')->nullable();
            $table->float('survey_charges_discount_amount')->nullable();
            $table->text('survey_charges_value_excld')->nullable();
            $table->text('survey_charges_ST_n_fed')->nullable();
            $table->text('survey_charges_provisionalsalestaxamount')->nullable();
            $table->text('survey_charges_value_inc_tax')->nullable();
            $table->text('bulletseal_affix_charges_paid_at')->nullable();
            $table->text('bulletseal_affix_charges_20')->nullable();
            $table->text('bulletseal_affix_charges_40')->nullable();
            $table->text('bulletseal_affix_charges_45')->nullable();
            $table->float('bulletseal_affix_charges_amount_usd')->nullable();
            $table->float('bulletseal_affix_charges_amount_pkr')->nullable();
            $table->float('bulletseal_affix_charges_discount_amount')->nullable();
            $table->text('bulletseal_affix_charges_value_excld')->nullable();
            $table->text('bulletseal_affix_charges_ST_n_fed')->nullable();
            $table->text('bulletseal_affix_charges_provisionalsalestaxamount')->nullable();
            $table->string('bulletseal_affix_charges_value_inc_tax')->nullable();
            $table->string('weighment_charges_paid_at')->nullable();
            $table->string('weighment_charges_20')->nullable();
            $table->string('weighment_charges_40')->nullable();
            $table->string('weighment_charges_45')->nullable();
            $table->float('weighment_charges_amount_usd')->nullable();
            $table->float('weighment_charges_amount_pkr')->nullable();
            $table->float('weighment_charges_discount_amount')->nullable();
            $table->string('weighment_charges_value_excld')->nullable();
            $table->string('weighment_charges_ST_n_fed')->nullable();
            $table->string('weighment_charges_provisionalsalestaxamount')->nullable();
            $table->string('weighment_charges_value_inc_tax')->nullable();
            $table->string('container_no')->nullable();
            $table->string('container_size')->nullable();
            $table->string('container_demurragedate')->nullable();
            $table->string('container_demurrageupto')->nullable();
            $table->string('container_status')->nullable();
            $table->string('container_releasedt')->nullable();
            $table->string('container_no_ofdays')->nullable();
            $table->string('container_machineno')->nullable();
            $table->string('totalval_ex_stax_fed')->nullable();
            $table->string('prov_sales_tax')->nullable();
            $table->string('totalinvoiceamount');
            $table->string('receiptno')->nullable();
            $table->integer('receiptdt')->nullable();
            $table->timestamps();
       });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('import_invoices');
    }
}
